export ZSH_DIR=$HOME/dotfiles/__DOTDIR/zsh
source $ZSH_DIR/checks.zsh

[[ -z $DISPLAY && $KDG_VTNR -eq 1 ]] && exec startx

#
# Browser
#

export BROWSER="open"

if [[ $IS_LINUX ]]; then
    if [ -n "$DISPLAY" ]; then
        BROWSER=chromium
    else
        BROWSER=links
    fi
fi

#
# Editor
#

export EDITOR="nvim"
export VISUAL=nvim
export HGEDITOR='vim'

#
# Language
#

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

#
# Term
#

export TERM="xterm-256color"
if [[ $IS_LINUX ]]; then
    export TERM=rxvt-unicode
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
	$HOME/.local/bin
	$HOME/bin
	$HOME/.gem/ruby/2.0.0/bin
	$HOME/.rbenv/bin
	$HOME/gocode/bin
	$HOME/edm/bin
	$path
)

export GOPATH=$HOME/gocode

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"

if [[ ! -d "$TMPPREFIX" ]]; then
  mkdir -p "$TMPPREFIX"
fi

#
# SSH Agent
#

SSHAGENT=/usr/bin/ssh-agent
SSHAGENTARGS="-s"
if [ -z "$SSH_AUTH_SOCK" -a -x "$SSHAGENT" ]; then
    eval `$SSHAGENT $SSHAGENTARGS`
    trap "kill $SSH_AGENT_PID" 0
fi
